CREATE TABLE TIPO_ARTICULO
(
    ID_TIPO SERIAL PRIMARY KEY,
    DESC_TIPO VARCHAR2(100)
);

CREATE TABLE ARTICULO
(
    ID_ARTICULO SERIAL PRIMARY KEY,
    DESC_ARTICULO VARCHAR2(100),
    PRECIO REAL,
    ID_TIPO INTEGER,
    RECETA BOOLEAN,
    FOREIGN KEY(ID_TIPO) REFERENCES TIPO_ARTICULO(ID_TIPO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PROVEEDORES
(
    ID_PROV SERIAL PRIMARY KEY,
    DESC_PROV VARCHAR2(100)
);

CREATE TABLE PROV_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_PROV INTEGER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_PROV) REFERENCES PROVEEDORES(ID_PROV) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE DEPOSITO
(
    ID_DEPOSITO SERIAL PRIMARY KEY,
    DESC_DEPOSITO VARCHAR2(100)
);

CREATE TABLE DEPOSITO_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_DEPOSITO INTEGER,
    CANTIDAD NUMBER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_DEPOSITO) REFERENCES DEPOSITO(DEPOSITO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CIUDAD
(

);

CREATE TABLE CLIENTE
(
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELLIDO VARCHAR2(30) NOT NULL,
    CI VARCHAR2(30) NOT NULL,
    CORREO VARCHAR2(30),
    TELEFONO VARCHAR(30),
    ID_CIUDAD INTEGER,
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE TURNO

CREATE TABLE EMPLEADO
(
    ID_EMPLEADO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELLIDO VARCHAR2(30) NOT NULL,
    CI VARCHAR2(30) NOT NULL,
    CARGO VARCHAR2(30) NOT NULL,
    TURNO

)

CREATE TABLE VENTAS 
(
 ID_VENTA SERIAL PRIMARY KEY,
 FECHA DATE DEFAULT CURRENT_DATE,
 MONTO_EXENTO REAL,
 MONTO_GRAVADA_5 REAL,
 MONTO_IVA_5 REAL,
 MONTO_GRAVADA_10 REAL,
 MONTO_IVA_10 REAL,
 ID_CLIENTE INTEGER,
 ID_EMPLEADO INTEGER
);