CREATE TABLE TIPO_ARTICULO
(
    ID_TIPO SERIAL PRIMARY KEY,
    DESC_TIPO VARCHAR2(100)
)

CREATE TABLE ARTICULO
(
    ID_ARTICULO SERIAL PRIMARY KEY,
    DESC_ARTICULO VARCHAR2(100),
    PRECIO REAL,
    ID_TIPO INTEGER,
    RECETA BOOLEAN,
    FOREIGN KEY(ID_TIPO) REFERENCES TIPO_ARTICULO(ID_TIPO) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE PROVEEDORES
(
    ID_PROV SERIAL PRIMARY KEY,
    DESC_PROV VARCHAR2(100)
)

CREATE TABLE PROV_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_PROV INTEGER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_PROV) REFERENCES PROVEEDORES(ID_PROV) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE DEPOSITO
(
    ID_DEPOSITO SERIAL PRIMARY KEY,
    DESC_DEPOSITO VARCHAR2(100)
)

CREATE TABLE DEPOSITO_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_DEPOSITO INTEGER,
    CANTIDAD NUMBER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_DEPOSITO) REFERENCES DEPOSITO(DEPOSITO) ON UPDATE CASCADE ON DELETE RESTRICT
)

