--INSERCION

INSERT INTO TIPO_ARTICULO (DESC_TIPO) 
VALUES ('Medicamento'), ('Cosmético');


INSERT INTO ARTICULO (DESC_ARTICULO, PRECIO, ID_TIPO, RECETA) 
VALUES ('Paracetamol 500mg', 1500, 1, TRUE);

INSERT INTO PROVEEDORES (DESC_PROV, TELEFONO, DIRECCION, RUC)
VALUES ('Distribuidora Salud', '0981123456', 'Av. Central 123', '80012345-6');

INSERT INTO PROV_ARTICULO (ID_ARTICULO, ID_PROV) 
VALUES (1, 1);

-- ACTUALIZAR

UPDATE ARTICULO 
SET PRECIO = PRECIO * 1.10 
WHERE ID_TIPO IN (SELECT ID_TIPO 
FROM TIPO_ARTICULO 
WHERE DESC_TIPO = 'Medicamento');

-- ELIMINAR

DELETE FROM CLIENTE 
WHERE ID_CLIENTE IN (3, 100, 2);

-- Vista de artículos con su tipo y precio
CREATE VIEW V_ARTICULOS_TIPO AS
SELECT A.DESC_ARTICULO, T.DESC_TIPO, A.PRECIO
FROM ARTICULO A
JOIN TIPO_ARTICULO T ON A.ID_TIPO = T.ID_TIPO;

--IN
--Artículos que pertenecen a tipos específicos
SELECT * FROM ARTICULO
WHERE ID_TIPO IN (1, 2);
--NOT IN
-- Proveedores que no ofrecen el artículo 1
SELECT * FROM PROVEEDORES
WHERE ID_PROV NOT IN (SELECT ID_PROV FROM PROV_ARTICULO WHERE ID_ARTICULO = 1);
-- Buscar clientes que tengan correo con dominio @gmail
SELECT * FROM CLIENTE
WHERE CORREO LIKE '%@gmail%';
--GROUP BY
-- Total de artículos vendidos por depósito
SELECT ID_DEPOSITO, SUM(CANTIDAD) AS TOTAL_VENDIDO
FROM DET_VENTAS
GROUP BY ID_DEPOSITO;
--BEETWEN
-- Ventas realizadas entre el 1 y 15 de mayo de 2025
SELECT * FROM VENTAS
WHERE FECHA BETWEEN '2025-05-01' AND '2025-05-15';