CREATE TABLE TIPO_ARTICULO
(
    ID_TIPO SERIAL PRIMARY KEY,
    DESC_TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE ARTICULO
(
    ID_ARTICULO SERIAL PRIMARY KEY,
    DESC_ARTICULO VARCHAR(100) NOT NULL,
    PRECIO REAL NOT NULL,
    ID_TIPO INTEGER,
    RECETA BOOLEAN,
    FOREIGN KEY(ID_TIPO) REFERENCES TIPO_ARTICULO(ID_TIPO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PROVEEDORES
(
    ID_PROV SERIAL PRIMARY KEY,
    DESC_PROV VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    RUC VARCHAR(100) NOT NULL
);

CREATE TABLE PROV_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_PROV INTEGER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_PROV) REFERENCES PROVEEDORES(ID_PROV) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE DEPOSITO
(
    ID_DEPOSITO SERIAL PRIMARY KEY,
    DESC_DEPOSITO VARCHAR(100) NOT NULL
);

CREATE TABLE DEPOSITO_ARTICULO
(
    ID_ARTICULO INTEGER,
    ID_DEPOSITO INTEGER,
    CANTIDAD INTEGER,
    FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ID_DEPOSITO) REFERENCES DEPOSITO(ID_DEPOSITO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CIUDAD
(
    ID_CIUDAD SERIAL PRIMARY KEY,
    DESC_CIUDAD VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTE
(
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    CI VARCHAR(30) NOT NULL,
    RUC VARCHAR(30),
    CORREO VARCHAR(30),
    TELEFONO VARCHAR(30),
    ID_CIUDAD INTEGER,
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE TURNO
(
    ID_TURNO SERIAL PRIMARY KEY,
    DESC_TURNO VARCHAR(50) NOT NULL
);

CREATE TABLE CARGO 
(
    ID_CARGO SERIAL PRIMARY KEY,
    DESC_CARGO VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLEADO
(
    ID_EMPLEADO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    CI VARCHAR(30) NOT NULL,
    ID_CARGO INTEGER,
    ID_TURNO INTEGER,
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_TURNO) REFERENCES TURNO(ID_TURNO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE METODO_PAGO
(
    ID_METODO_PAGO SERIAL PRIMARY KEY,
    DESC_METODO_PAGO VARCHAR(50) NOT NULL
);

CREATE TABLE VENTAS 
(
 ID_VENTA SERIAL PRIMARY KEY,
 FECHA DATE DEFAULT CURRENT_DATE,
 MONTO_EXENTO REAL,
 MONTO_GRAVADA_5 REAL,
 MONTO_IVA_5 REAL,
 MONTO_GRAVADA_10 REAL,
 MONTO_IVA_10 REAL,
 ID_CLIENTE INTEGER,
 ID_EMPLEADO INTEGER,
 ID_METODO_PAGO INTEGER,
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON UPDATE CASCADE ON DELETE RESTRICT,
 FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE DET_VENTAS
(
    ID_VENTA INTEGER,
    ID_ARTICULO INTEGER,
    ID_DEPOSITO INTEGER,
    CANTIDAD INTEGER,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITO(ID_DEPOSITO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE COMPRA
(
    ID_COMPRA SERIAL PRIMARY KEY,
    FECHA DATE,
    ID_PROV INTEGER,
    MONTO_EXENTO REAL,
    MONTO_GRAVADA_5 REAL,
    MONTO_IVA_5 REAL,
    MONTO_GRAVADA_10 REAL,
    MONTO_IVA_10 REAL,
    FOREIGN KEY (ID_PROV) REFERENCES PROVEEDORES(ID_PROV) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE DET_COMPRA
(
    ID_COMPRA INTEGER,
    ID_ARTICULO INTEGER,
    ID_DEPOSITO INTEGER,
    CANTIDAD INTEGER,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITO(ID_DEPOSITO) ON UPDATE CASCADE ON DELETE RESTRICT
);